#include "instr.h"

const op_info_t op_info_table[] = {
    // 0x00
    { .instr_exe = instr_exe_add_Eb_Gb }
}
<<<<<<< HEAD

modrm16_info modrm16_info_table[] {
    /***********
     * MOD 0x0 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, disp_size = 0 },
    { .calc_addr = calc_addr16_offset, disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, disp_size = 0 },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = 0 },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = 0 },
    { .calc_addr = calc_addr16_offset, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = 0 },

    /***********
     * MOD 0x1 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(byte_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(byte_t) },

    /***********
     * MOD 0x2 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base_index, .base = X86_REG_BX, .index = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_SI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_DI, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base,.base = X86_REG_BP, .disp_size = sizeof(word_t) },
    { .calc_addr = calc_addr16_base, .base = X86_REG_BX, .disp_size = sizeof(word_t) },

    /***********
     * MOD 0x3 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
}

modrm32_info_t modrm_info_table[] {
    /***********
     * MOD 0x0 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_scale_index_base, .disp_size = 0, .sib = true },
    { .calc_addr = calc_addr32_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },
    { .calc_addr = calc_addr32_base, .disp_size = 0, .sib = false },

    /***********
     * MOD 0x1 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(byte_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(byte_t), .sib = false },

    /***********
     * MOD 0x2 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_scale_index_base_offset, .disp_size = sizeof(dword_t), .sib = true },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },
    { .calc_addr = calc_addr32_base_offset, .disp_size = sizeof(dword_t), .sib = false },

    /***********
     * MOD 0x3 *
     ***********/
    // Reg 0x0 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x1 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x2 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x3 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x4 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x5 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x6 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    // Reg 0x7 : R/M 0x0-0x7
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
    { .calc_addr = NULL },
}

modrm32_info modrm_info_sib_override = {
    .calc_addr = calc_addr32_scale_index_offset,
    .disp_size = sizeof(dword_t),
    .sib = true
};
=======
>>>>>>> origin/master
